name: spider
description: Spider is a client library for handling (authenticated) multi-threaded disposable network calls,  data parsing and authentication in applications.
version: 0.1.0
author: Ayush Suman
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.2
  flutter_secure_storage: ^4.2.0
  localstorage: ^4.0.0+1
